### ISSUE TITLE
Serveur en page d'accueil et création du mdp

### ISSUE THREAD

**Issue by Anamabruja** [RxLaboratory/Ramses#179]
- [ ] Afficher la page du serveur en page d'accueil quand on ouvre l'appli -> #181
- [ ] Bloquer "current password" quand on crée un mdp pour la première fois-> #182
- [ ] Ecrire "repeat new password" en dessous du "new password" -> #183
