### ISSUE TITLE
TODO before release

### ISSUE THREAD

**Issue by Nico-Duduf** [RxLaboratory/Ramses#262]
## Prepare DB

- [ ] Set the default sqlite file
- [ ] Check the default data in mySQL

## Test server install script

- [ ] Test install with mySQL
- [ ] Test install with SQLite

## Test server update script

- [ ] Test update with mySQL
- [ ] Test update with SQLite

## Tests

- [ ] Thoroughly test with mySQL
- [ ] Thoroughly test with SQLite

## Build server

- [ ] Check version number
- [ ] Merge dev branch
- [ ] Zip

## Build Py API

- [ ] Check version number
- [ ] Zip

## Build Maya Add-on

- [ ] Check version number
- [ ] Merge dev branch
- [ ] Zip

## Build Maya Rubika addon

- [ ] Check version number
- [ ] Merge dev branch
- [ ] Zip

## Build Client

- [ ] Check version number
- [ ] Linux .deb openSSL 1.0
- [ ] Linux .deb openSSL 1.1
- [ ] Linux .appImage openSSL 1.1
- [ ] Mac OS
- [ ] Windows
- [ ] Merge dev branch

## Update doc and publish

- [ ] Update server doc (install & update instructions)
- [ ] Update changelog and known issues
- [ ] Publish doc
- [ ] Github release with all assets
- [ ] Publish on rxlaboratory.org
